# name of the work flow
name: Build
on: [pull_request]
jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [11, 14]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Clean build
        run: ./gradlew clean build --stacktrace

      - name: Upload Demo APK
        uses: actions/upload-artifact@v1
        with:
          name: Demo APK Artifacts
          path: app/build/outputs/apk/demo/debug/app-demo-debug.apk

      - name: Upload Stage APK
        uses: actions/upload-artifact@v1
        with:
          name: Stage APK Artifacts
          path: app/build/outputs/apk/stage/debug/app-stage-debug.apk

      - name: Upload Prod APK
        uses: actions/upload-artifact@v1
        with:
          name: Prod APK Artifacts
          path: app/build/outputs/apk/prod/debug/app-prod-debug.apk

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/prodRelease
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload prod bundle
        uses: actions/upload-artifact@v2
        with:
          name: Prod AAB Artifacts
          path: ${{steps.sign.outputs.signedReleaseFile}}